# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iosdevspot.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: iOSDevSpot
  avatar: avatar.png
  gravatar: 92d407160aaa83cafc956e8daa529f92
  description: "A idéia de criar um site de screencasts para iOS não é nova para mim, mas sim uma idéia que foi amadurecendo com o tempo e experiência de mercado. Existem muitos modelos de sites de screencasts conhecidos não apenas de iOS mas de Rails, Vim e muitos outros assuntos. A questão para eu ter dado inicio a mais um site de screencast é que por mais que existam varias opções não existe muitas opções em português, mas de maneira pratica e descontraída pretendo levar esse projeto a frente não apenas para iOS mas também outras plataformas Pretendo convidar algumas pessoas para participarem de alguns casts especiais para galera, mostrando que tem muita galera que manja muito por esse Brasil a fora." # used by search engines
  
  # Header and footer text
  header_text: >
  footer_text: >
   <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licença Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />O trabalho <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">iOSDevSpot</span> está licenciado com uma Licença <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons - Atribuição, Não Comercial, Compartilha Igual 4.0 Internacional</a>.
   <br />
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: "iosdevspot"
  flickr: 
  github: "iOSDevSpot/"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "iosdevspot"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname: iosdevpost
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Próximo"
  str_prev: "Anterior"
  str_continue_reading: "Continuar lendo"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
